=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/schema/device.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	EasyLib XML Schema Definition

	Copyright (c) 2007-2010 Technische Universität München, Lehrstuhl Informatik VI
		http://www6.in.tum.de/

	Copyright (c) 2007-2010 REC GmbH
		http://www.servicerobotics.eu/
-->
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:dev="http://easykit.informatik.tu-muenchen.de/schema/device"
	xmlns:md="http://easykit.informatik.tu-muenchen.de/schema/model"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:kv="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
	xmlns:desc="http://easykit.informatik.tu-muenchen.de/schema/description"
	targetNamespace="http://easykit.informatik.tu-muenchen.de/schema/device"
	attributeFormDefault="qualified"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/translation"
		schemaLocation="translation.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/model"
		schemaLocation="model.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/plugin"
		schemaLocation="plugin.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/template"
		schemaLocation="template.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/variable"
		schemaLocation="variable.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
		schemaLocation="keyvalue.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/description"
		schemaLocation="description.xsd"/>

	<!-- Root node -->
	<xs:element name="device" type="dev:deviceType"/>

	<!-- Recursive definition of a device -->
	<xs:complexType name="deviceType">

		<xs:sequence>
			<!-- The translations element specifies translations for key phrases specified
			     below this device specification. See the translation.xsd schema file for how
			     the element and its children are to be specified. -->
			<xs:element name="translations" type="tr:translationType" minOccurs="0" maxOccurs="1"/>

			<!-- The inputs node contains the specification of a device's inputs ("sensors") -->
			<xs:element name="inputs" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="input" type="dev:inputVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- The output node contains the specification of a device's outputs ("actors") -->
			<xs:element name="outputs" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="output" type="dev:outputVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- The state node contains the specification of a device's state variables -->
			<xs:element name="state" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="statevar" type="dev:stateVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- The config node contains a specification of a device's configuration variables -->
			<xs:element name="config" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="configvar" type="dev:configVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- The subdevices node contains a recursive specification of "smaller" devices
			     that make up the current device. This technique is used to be able to build
			     devices out of smaller components. -->
			<xs:element name="subdevices" type="dev:subdevicesType" minOccurs="0" maxOccurs="1"/>

			<!-- The inventory specification of a device holds all resources that have to be
			     managed at this level. They can be used to define constraints that ought to
			     be obeyed when the respective units or unit variants are instantiated. -->
			<xs:element name="provides" type="dev:providesType" minOccurs="0" maxOccurs="1"/>

			<!-- Unit requirements specification. This section defines the resources each of
			     the unit variants will use when they are instantiated. This is needed to
			     determine when to disable instantiation of the respective unit or other units
			     that depend on the same (subset of) resources. -->
			<xs:element name="requires" type="dev:requiresType" minOccurs="0" maxOccurs="1"/>

			<!-- Unit type specializations. Needed to define the initial data types for the
			     unit variants available at this device level. Same syntax as in model.xsd. -->
			<xs:element name="utspecs" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="utspec" type="md:unitTypeSpecializationType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- Unit variant specification. This section defines the units that may be
			     instantiated at this device level. Note the requirements for unit instantiation
			     defined above, they influence which units will actually be available during
			     runtime. Same syntax as in model.xsd. -->
			<xs:element name="units" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="unit" type="dev:deviceUnitType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- Resource map specification. This section defines resource mappings for the current
			     device. Resource mappings are used to define which resource requirements are mapped
			     to which hardware resource in the device. This is necessary in case the resource
			     requirement is not specified directly, but instead a class name of a resource is
			     specified. All resource requirements must be fulfilled before the device can be
			     programmed. -->
			<xs:element name="resourcemappings" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="instance" type="dev:resourceMappingInstanceType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- Plugin filenames for device -->
			<xs:element name="plugins" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="plugin" type="plugin:pluginType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<!-- GUI related information element. Note that the element for a specific
			     device must be located below in the respective <dev:device> node, not
			     at the parent level (i.e., if a device has subdevices, then the
			     <dev:guiinfo> element for each subdevice must be located inside the
			     <dev:subdevices><dev:subdevice><dev:guiinfo> element!) -->
			<xs:element name="guiinfo" type="dev:guiInfoType" minOccurs="0" maxOccurs="1"/>

			<!-- Code generation information element. -->
			<xs:element name="codegen" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="platforms" type="dev:platformListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="global" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="local" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="open" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="start" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="read" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="write" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="stop" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="close" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>

		<!-- Device identification, for external references -->
		<!--<xs:attribute name="id" type="xs:ID" use="required"/>-->
		<xs:attribute name="id" type="xs:string" use="required"/>

		<!-- Flag determining whether the device can "live on its own".
		     This controls whether the user may select the respective
		     device as toplevel part in his model. --> 
		<xs:attribute name="toplevel" type="xs:boolean" use="optional" default="false"/>

		<!-- Flag determining whether the connection to the device should be established automatically -->
		<xs:attribute name="autoconnect" type="xs:boolean" use="optional" default="false"/>

		<!-- Flag if the device is currently hidden (used with PnP) -->
		<xs:attribute name="hidden" type="xs:boolean" use="optional"/>

	</xs:complexType>

	<!-- Definition of platform list type -->
	<xs:complexType name="platformListType">
		<xs:sequence>
			<xs:element name="platform" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition of input variable type -->
	<xs:complexType name="inputVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definition of output variable type -->
	<xs:complexType name="outputVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definition of input variable type -->
	<xs:complexType name="stateVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definition of configuration variable type -->
	<xs:complexType name="configVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<!-- Definition of subdevices type -->
	<xs:complexType name="subdevicesType">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<!-- Reference to an externally defined device -->
				<xs:element name="deviceref">
					<xs:complexType>
						<!-- Identification of referenced external device -->
						<xs:attribute name="id" type="xs:string" use="required"/>

						<!-- Instance name of this device reference -->
						<xs:attribute name="instanceName" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>

				<!-- Recursive device definition -->
				<xs:element name="device" type="dev:deviceType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition of provides type -->
	<xs:complexType name="providesType">
		<xs:sequence>
			<!-- A resource item definition -->
			<xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="class" type="xs:string" use="optional" default=""/>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="quantity" type="xs:integer" use="optional" default="1"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition of requires type -->
	<xs:complexType name="requiresType">
		<xs:sequence>
			<xs:element name="utspecrequirements" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<!-- Requirement map for the respective unit type variant -->
					<xs:sequence>
						<xs:element name="resourceclass" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="class" type="xs:string" use="required"/>
								<xs:attribute name="quantity" type="xs:integer" use="optional" default="1"/>
							</xs:complexType>
						</xs:element>

						<!--
						Currently disabled, because we might not need this
						<xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="quantity" type="xs:integer" use="required"/>
							</xs:complexType>
						</xs:element>
						-->

					</xs:sequence>
					<xs:attribute name="utspec" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition of device unit type (like md:unitType, but with some other elements) -->
	<xs:complexType name="deviceUnitType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="inConnectorExprs" type="md:varExprsType"/>
			<xs:element minOccurs="0" maxOccurs="1" name="stateVarExprs" type="md:varExprsType"/>
			<!-- No inVarExprs -->

			<xs:element minOccurs="0" maxOccurs="1" name="unitRequirements" type="dev:unitRequirementsType"/>

			<!-- GUI related information element -->
			<xs:element name="guiinfo" type="dev:guiInfoType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="attributes" type="kv:keyValueRootType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>

		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="utspec" type="xs:IDREF"/>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>

	<!-- Definition of unit requirements type -->
	<xs:complexType name="unitRequirementsType">
		<xs:choice maxOccurs="unbounded">
			<!-- Either specify the name of a resource... -->
			<xs:element name="resource">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="quantity" type="xs:positiveInteger" use="optional" default="1"/>
				</xs:complexType>
			</xs:element>

			<!-- ... or the name of a resource class -->
			<xs:element name="resourceclass">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="quantity" type="xs:positiveInteger" use="optional" default="1"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<!-- Definition of resource mappings instance type -->
	<xs:complexType name="resourceMappingInstanceType">
		<xs:sequence>
			<xs:element name="classmapping" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="classname" type="xs:string" use="required"/>
					<xs:attribute name="index" type="xs:nonNegativeInteger" use="required"/>
					<xs:attribute name="targetdevice" type="xs:string" use="required"/>
					<xs:attribute name="targetinstance" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="instancename" type="xs:string" use="required"/>
		<xs:attribute name="instanceindex" type="xs:nonNegativeInteger" use="required"/>
	</xs:complexType>

	<!-- Definition of GUI related information type -->
	<xs:complexType name="guiInfoType">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="description" type="dev:descriptionType"/>

			<!-- Optional list of annotations that can be used to categorize this item.
			     Reserved annotations:
			      * skill (int)         Denotes the level of difficulty of this item.
			      * keywords (keyValue) Child element containing keywords that can be used
			                            to define search terms for items (e.g., to find the
			                            "Additon" unit with the search term "plus").
			-->
			<xs:element minOccurs="0" maxOccurs="1" name="annotations" type="kv:keyValueRootType"/>
    </xs:sequence>
    <xs:attribute name="display" type="dev:variableDisplayType" default="visible" use="optional"/>
  </xs:complexType>

  <xs:simpleType name="variableDisplayType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="visible"/>
      <xs:enumeration value="hidden"/>
    </xs:restriction>
  </xs:simpleType>

	<!-- Definition of device description type (needed for GUI) -->
	<xs:complexType name="descriptionType">
		<xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="name" type="dev:briefDescription"/>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:element name="detailed" type="xs:string"/>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:choice>
					<xs:element name="icon" type="dev:filespec"/>
					<xs:element name="iconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:sequence minOccurs="0" maxOccurs="1">
				<xs:choice>
					<xs:element name="schematicIcon" type="dev:filespec"/>
					<xs:element name="schematicIconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>

	<!-- Definition of brief description type -->
	<xs:simpleType name="briefDescription">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Definition of file name specification type -->
	<xs:complexType name="filespec">
		<xs:attribute type="xs:string" name="filename" use="required"/>
	</xs:complexType>

</xs:schema>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/devices/robview/DataExchange/client/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<dev:device
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/device device.xsd"
	xmlns:dev="http://easykit.informatik.tu-muenchen.de/schema/device"
	xmlns:md="http://easykit.informatik.tu-muenchen.de/schema/model"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	dev:id="REC GmbH Data Exchange Client" dev:toplevel="true">

  <dev:translations>
  </dev:translations>

	<dev:inputs>
		<dev:input var:type="int16" var:varname="in0">
			<var:default var:val="0"/>
		</dev:input>
	</dev:inputs>

	<dev:outputs>
		<dev:output var:type="int16" var:varname="out0">
			<var:default var:val="0"/>
		</dev:output>
	</dev:outputs>

	<dev:state>
	</dev:state>

	<dev:config>
		<dev:configvar var:type="string" var:varname="address">
			<var:default var:val="127.0.0.1"/>
		</dev:configvar>
    <dev:configvar var:type="bool" var:varname="autoReconnect">
      <var:default var:val="true"/>
    </dev:configvar>
    <dev:configvar var:type="int32" var:varname="queuedSendingInterval">
      <var:default var:val="200"/>
    </dev:configvar>
  </dev:config>

	<dev:subdevices>
	</dev:subdevices>
	
	<!-- Plugin filename -->
	<dev:plugins>
		<dev:plugin plugin:type="simulation" plugin:library="device_dataexchange_client_simulation"/>
		<dev:plugin plugin:type="dialog" plugin:library="device_dataexchange_client_gui"/>
	</dev:plugins>

  <dev:guiinfo>
    <dev:description>
      <dev:name>Data Exchange Client</dev:name>
      <dev:detailed>REC GmbH Data Exchange Client</dev:detailed>
      <dev:icon dev:filename="icons/client.png"/>
    </dev:description>
  </dev:guiinfo>

</dev:device>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/devices/generic/device.xml
<?xml version="1.0" encoding="UTF-8"?>
<dev:device
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/device device.xsd"
	xmlns:dev="http://easykit.informatik.tu-muenchen.de/schema/device"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:md="http://easykit.informatik.tu-muenchen.de/schema/model"
	dev:id="Generic" dev:toplevel="true">

	<dev:translations>
	</dev:translations>

	<dev:subdevices>

		<dev:device dev:id="Logic">
			<dev:subdevices>
				<dev:device dev:id="Logic_logicops">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Logic AND" />
						<dev:unit dev:type="REC GmbH Logic OR" />
						<dev:unit dev:type="REC GmbH Logic NAND" />
						<dev:unit dev:type="REC GmbH Logic NOR" />
						<dev:unit dev:type="REC GmbH Logic XOR" />
						<dev:unit dev:type="REC GmbH Logic NOT" />
					</dev:units>
				</dev:device>
				<dev:device dev:id="Logic_triggered">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Logic AND FL" />
						<dev:unit dev:type="REC GmbH Logic NAND FL" />
						<dev:unit dev:type="REC GmbH Logic RS" />
						<dev:unit dev:type="REC GmbH Sample And Hold Element" />
					</dev:units>
				</dev:device>
				<dev:device dev:id="Logic_bitwise">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Bitwise And" />
						<dev:unit dev:type="REC GmbH Bitwise Exclusive Or" />
						<dev:unit dev:type="REC GmbH Bitwise Not" />
						<dev:unit dev:type="REC GmbH Bitwise Or" />
						<dev:unit dev:type="REC GmbH Bitwise Shift Left" />
						<dev:unit dev:type="REC GmbH Bitwise Shift Right" />
						<dev:unit dev:type="REC GmbH Bitwise Test" />
					</dev:units>
				</dev:device>
			</dev:subdevices>
			<dev:units>
				<dev:unit dev:type="REC GmbH Counter Up"/>
				<dev:unit dev:type="REC GmbH Counter Down"/>
				<dev:unit dev:type="REC GmbH Multiplexer"/>
				<dev:unit dev:type="REC GmbH Demultiplexer"/>
			</dev:units>
		</dev:device>

		<dev:device dev:id="Math">
			<dev:subdevices>
				<dev:device dev:id="Math_arithops">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Basic Addition" />
						<dev:unit dev:type="REC GmbH Basic Division" />
						<dev:unit dev:type="REC GmbH Basic Modulo" />
						<dev:unit dev:type="REC GmbH Basic Multiplication" />
						<dev:unit dev:type="REC GmbH Basic Subtraction" />
					</dev:units>
				</dev:device>
				<dev:device dev:id="Math_compareops">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Basic Equality" />
						<dev:unit dev:type="REC GmbH Basic Greater" />
						<dev:unit dev:type="REC GmbH Basic Greater Equal" />
						<dev:unit dev:type="REC GmbH Basic Inequality" />
						<dev:unit dev:type="REC GmbH Basic Less" />
						<dev:unit dev:type="REC GmbH Basic Less Equal" />
					</dev:units>
				</dev:device>
				<dev:device dev:id="Math_functions">
					<dev:subdevices>
						<!--<dev:device dev:id="Math_trigonometry">
							<dev:subdevices>
							</dev:subdevices>
							<dev:units>
								<dev:unit dev:type="REC GmbH Basic Atan"/>
							</dev:units>
						</dev:device>-->
					</dev:subdevices>
					<dev:units>
						<dev:unit dev:type="REC GmbH Transferfunction"/>
						<dev:unit dev:type="REC GmbH Basic Minimum"/>
						<dev:unit dev:type="REC GmbH Basic Maximum"/>
						<dev:unit dev:type="REC GmbH Basic Absolute Value"/>
						<dev:unit dev:type="REC GmbH Robotino Scale"/>
					</dev:units>
				</dev:device>
				<dev:device dev:id="Math_arrays">
					<dev:subdevices/>
					<dev:units>
						<dev:unit dev:type="REC GmbH Float Array Composer" />
						<dev:unit dev:type="REC GmbH Float Array Decomposer" />
						<dev:unit dev:type="REC GmbH Float Array Splitter" />
						<dev:unit dev:type="REC GmbH Float Array Index Access" />
					</dev:units>
				</dev:device>
			</dev:subdevices>
			<dev:units>
			</dev:units>
		</dev:device>

		<dev:device dev:id="Vectormath">
			<dev:subdevices>
				<dev:device dev:id="Vectormath_vectorops">
					<dev:units>
						<dev:unit dev:type="REC GmbH Vector2f Addition"/>
						<dev:unit dev:type="REC GmbH Vector2f Subtraction"/>
						<dev:unit dev:type="REC GmbH Vector2f Dot"/>
						<dev:unit dev:type="REC GmbH Vector2f Norm"/>
						<!--<dev:unit dev:type="REC GmbH Vector3f Cross"/>-->
					</dev:units>
				</dev:device>
				<dev:device dev:id="Vectormath_elementops">
					<dev:units>
						<dev:unit dev:type="REC GmbH Vector2f Element Addition"/>
						<dev:unit dev:type="REC GmbH Vector2f Element Subtraction"/>
						<dev:unit dev:type="REC GmbH Vector2f Element Multiplication"/>
						<dev:unit dev:type="REC GmbH Vector2f Element Division"/>
					</dev:units>
				</dev:device>
				<dev:device dev:id="Vectormath_transform">
					<dev:units>
						<dev:unit dev:type="REC GmbH Vector2f Cartesian2Vector"/>
						<dev:unit dev:type="REC GmbH Vector2f Polar2Vector"/>
						<dev:unit dev:type="REC GmbH Vector2f Vector2Cartesian"/>
						<dev:unit dev:type="REC GmbH Vector2f Vector2Polar"/>
						<dev:unit dev:type="REC GmbH Vector2f Rotate"/>
					</dev:units>
				</dev:device>
			</dev:subdevices>
		</dev:device>

		<dev:device dev:id="Display">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Oscilloscope" />
				<!--<dev:unit dev:type="REC GmbH LaserRangeFinderDataDisplay" />-->
			</dev:units>
		</dev:device>

		<dev:device dev:id="Cv">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Segmenter" >
					<dev:guiinfo dev:display="hidden">
						<dev:description />
					</dev:guiinfo>
				</dev:unit>
				<dev:unit dev:type="REC GmbH Segment Extractor" >
					<dev:guiinfo dev:display="hidden">
						<dev:description />
					</dev:guiinfo>
				</dev:unit>
				<dev:unit dev:type="REC GmbH Line Detector" />
				<dev:unit dev:type="REC GmbH ROI" />
				<dev:unit dev:type="REC GmbH ImageInfo" />
				<dev:unit dev:type="REC GmbH Colorspace Conversion" />
				<dev:unit dev:type="REC GmbH ColorRangeFinder" />
				<dev:unit dev:type="REC GmbH SegmentTracker" />
				<dev:unit dev:type="REC GmbH ImageFilter" />
				<dev:unit dev:type="REC GmbH Calibration" />
				<dev:unit dev:type="REC GmbH Marker Detection" />
				<dev:unit dev:type="REC GmbH Marker Position" />
			</dev:units>
		</dev:device>

		<dev:device dev:id="Generators">
			<dev:subdevices/>
			<dev:utspecs>
				<dev:utspec md:id="REC_GmbH_Generators_float">
					<md:spec md:curr="float" md:type="T"/>
				</dev:utspec>
			</dev:utspecs>
			<dev:units>
				<dev:unit dev:type="REC GmbH Constant" dev:utspec="REC_GmbH_Generators_float">
					<dev:guiinfo>
						<dev:description>
							<dev:icon dev:filename="const.png"/>
						</dev:description>
					</dev:guiinfo>
				</dev:unit>
				<dev:unit dev:type="REC GmbH ARB generator" />
				<dev:unit dev:type="REC GmbH Robotino Timer" />
				<dev:unit dev:type="REC GmbH Random Generator" />
			</dev:units>
		</dev:device>

		<dev:device dev:id="Filter">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Mean Filter" />
			</dev:units>
		</dev:device>

		<dev:device dev:id="Navigation">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Position Driver" />
				<dev:unit dev:type="REC GmbH Path Driver" />
				<dev:unit dev:type="REC GmbH Constant Pose" />
				<dev:unit dev:type="REC GmbH Pose Composer" />
				<dev:unit dev:type="REC GmbH Pose Decomposer" />
				<dev:unit dev:type="REC GmbH Path Composer" />
				<dev:unit dev:type="REC GmbH Path Decomposer" />
				<!--<dev:unit dev:type="REC GmbH Position View" />-->
				<dev:unit dev:type="REC GmbH Obstacle Avoidance" />
			</dev:units>
		</dev:device>

		<dev:device dev:id="Input devices">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH ControlPanel"/>
				<dev:unit dev:type="REC GmbH Slider"/>
			</dev:units>
		</dev:device>

		<dev:device dev:id="Dataexchange">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Image Reader"/>
				<dev:unit dev:type="REC GmbH Image Writer"/>
				<dev:unit dev:type="REC GmbH Value Writer"/>
				<dev:unit dev:type="REC GmbH Value Reader"/>
			</dev:units>
		</dev:device>

		<dev:device dev:id="Custom">
			<dev:subdevices/>
			<dev:units>
				<dev:unit dev:type="REC GmbH Lua Script"/>
			</dev:units>
		</dev:device>

	</dev:subdevices>

</dev:device>
