=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/schema/unit.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	EasyLib XML Schema Definition

	Copyright (c) 2007-2010 Technische Universität München, Lehrstuhl Informatik VI
		http://www6.in.tum.de/

	Copyright (c) 2007-2010 REC GmbH
		http://www.servicerobotics.eu/
-->
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:kv="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:desc="http://easykit.informatik.tu-muenchen.de/schema/description"
	targetNamespace="http://easykit.informatik.tu-muenchen.de/schema/unit"
	attributeFormDefault="qualified"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
		schemaLocation="keyvalue.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/plugin"
		schemaLocation="plugin.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/translation"
		schemaLocation="translation.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/template"
		schemaLocation="template.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/variable"
		schemaLocation="variable.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/description"
		schemaLocation="description.xsd"/>

	<xs:element name="unit">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">

				<!-- The translations element specifies translations for key phrases specified
				     below this device specification. See the translation.xsd schema file for how
				     the element and its children are to be specified. -->
				<xs:element name="translations" type="tr:translationType" minOccurs="0" maxOccurs="1"/>

				<xs:element name="unittypes" type="unit:unittypesType" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="unittypesType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="unittype" type="unit:unittypeType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unittypeType">
		<xs:sequence>
			<xs:element name="typeTemplates">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="typeTemplate" type="var:typeTemplateType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="statevar" type="unit:stateVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="guiinfo" type="unit:guiinfoType"/>

			<xs:element name="plugins" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="plugin" type="plugin:pluginType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="codegen" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="global" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="local" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="start" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="step" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="stop" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="connectorSideType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top"/>
			<xs:enumeration value="bottom"/>
			<xs:enumeration value="left"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="in"/>
			<xs:enumeration value="out"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="descriptionType">
		<xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="name" type="unit:briefDescription"/>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:element name="detailed" type="xs:string"/>
			</xs:sequence>
			<xs:sequence>
				<xs:choice>
					<xs:element name="icon" type="unit:filespec"/>
					<xs:element name="iconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:choice>
					<xs:element name="schematicIcon" type="unit:filespec"/>
					<xs:element name="schematicIconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="info" type="unit:stateVariableDescriptionType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="briefDescription">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="filespec">
		<xs:attribute type="xs:string" name="filename" use="required"/>
	</xs:complexType>

	<xs:complexType name="guiinfoType">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="1" name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="1" maxOccurs="1" name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="layout" type="unit:stateVariableGuiInfoType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description" type="unit:descriptionType"/>

			<!-- Optional list of annotations that can be used to categorize this item.
			     Reserved annotations:
			      * skill (int)         Denotes the level of difficulty of this item.
			      * keywords (keyValue) Child element containing keywords that can be used
			                            to define search terms for items.
			-->
			<xs:element minOccurs="0" maxOccurs="1" name="annotations" type="kv:keyValueRootType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="variableGuiInfoType">
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="side" type="unit:connectorSideType" use="required"/>
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
				<xs:attribute name="valueDisplay" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="variableDisplayType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible"/>
			<xs:enumeration value="hidden"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="variableDescriptionType">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="pluginType">
		<xs:attribute type="xs:string" name="easygenfilename" use="optional"/>
		<xs:attribute type="xs:string" name="easylabfilename" use="optional"/>
	</xs:complexType>

	<xs:complexType name="implType" mixed="true"/>

</xs:schema>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/math/ArithOps/Mult.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>
		<unit:unittype unit:id="REC GmbH Basic Multiplication">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="float" var:varname="f1">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f2">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f3">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f4">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f5">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f6">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f7">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f8">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f9">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="f10">
						<var:default var:val="1"/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="float" var:varname="product">
						<var:default var:val="0"/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state/>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="f1" unit:side="left"/>
						<unit:layout unit:varname="f2" unit:side="left"/>
						<unit:layout unit:varname="f3" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f4" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f5" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f6" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f7" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f8" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f9" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="f10" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="product" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state/>

				<unit:description>
					<unit:name>Multiplication</unit:name>
					<unit:icon unit:filename="mult.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="f1">
								<unit:description>Factor[ 1]</unit:description>
							</unit:info>
							<unit:info unit:varname="f2">
								<unit:description>Factor[ 2]</unit:description>
							</unit:info>
							<unit:info unit:varname="f3">
								<unit:description>Factor[ 3]</unit:description>
							</unit:info>
							<unit:info unit:varname="f4">
								<unit:description>Factor[ 4]</unit:description>
							</unit:info>
							<unit:info unit:varname="f5">
								<unit:description>Factor[ 5]</unit:description>
							</unit:info>
							<unit:info unit:varname="f6">
								<unit:description>Factor[ 6]</unit:description>
							</unit:info>
							<unit:info unit:varname="f7">
								<unit:description>Factor[ 7]</unit:description>
							</unit:info>
							<unit:info unit:varname="f8">
								<unit:description>Factor[ 8]</unit:description>
							</unit:info>
							<unit:info unit:varname="f9">
								<unit:description>Factor[ 9]</unit:description>
							</unit:info>
							<unit:info unit:varname="f10">
								<unit:description>Factor[ 10]</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="product">
								<unit:description>Product</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state/>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_math_mult_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_math_mult_gui"/>
			</unit:plugins>

		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/navigation/PathComposer.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Path Composer">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="path" var:varname="p0">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p1">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p2">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p3">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p4">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p5">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p6">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p7">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p8">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p9">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p10">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p11">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p12">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p13">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p14">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p15">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p16">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p17">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p18">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="path" var:varname="p19">
						<var:default var:val=""/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="path" var:varname="path">
						<var:default var:val=""/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="p0" unit:side="left"/>
						<unit:layout unit:varname="p1" unit:side="left"/>
						<unit:layout unit:varname="p2" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p3" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p4" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p5" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p6" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p7" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p8" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p9" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p10" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p11" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p12" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p13" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p14" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p15" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p16" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p17" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p18" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="p19" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="path" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>Path composer</unit:name>
					<unit:icon unit:filename="icons/icon.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="p0">
								<unit:description>Path[ 1]</unit:description>
							</unit:info>
							<unit:info unit:varname="p1">
								<unit:description>Path[ 2]</unit:description>
							</unit:info>
							<unit:info unit:varname="p2">
								<unit:description>Path[ 3]</unit:description>
							</unit:info>
							<unit:info unit:varname="p3">
								<unit:description>Path[ 4]</unit:description>
							</unit:info>
							<unit:info unit:varname="p4">
								<unit:description>Path[ 5]</unit:description>
							</unit:info>
							<unit:info unit:varname="p5">
								<unit:description>Path[ 6]</unit:description>
							</unit:info>
							<unit:info unit:varname="p6">
								<unit:description>Path[ 7]</unit:description>
							</unit:info>
							<unit:info unit:varname="p7">
								<unit:description>Path[ 8]</unit:description>
							</unit:info>
							<unit:info unit:varname="p8">
								<unit:description>Path[ 9]</unit:description>
							</unit:info>
							<unit:info unit:varname="p9">
								<unit:description>Path[ 10]</unit:description>
							</unit:info>
							<unit:info unit:varname="p10">
								<unit:description>Path[ 11]</unit:description>
							</unit:info>
							<unit:info unit:varname="p11">
								<unit:description>Path[ 12]</unit:description>
							</unit:info>
							<unit:info unit:varname="p12">
								<unit:description>Path[ 13]</unit:description>
							</unit:info>
							<unit:info unit:varname="p13">
								<unit:description>Path[ 14]</unit:description>
							</unit:info>
							<unit:info unit:varname="p14">
								<unit:description>Path[ 15]</unit:description>
							</unit:info>
							<unit:info unit:varname="p15">
								<unit:description>Path[ 16]</unit:description>
							</unit:info>
							<unit:info unit:varname="p16">
								<unit:description>Path[ 17]</unit:description>
							</unit:info>
							<unit:info unit:varname="p17">
								<unit:description>Path[ 18]</unit:description>
							</unit:info>
							<unit:info unit:varname="p18">
								<unit:description>Path[ 19]</unit:description>
							</unit:info>
							<unit:info unit:varname="p19">
								<unit:description>Path[ 20]</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="path">
								<unit:description>Path[]</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_navigation_path_composer_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_navigation_path_composer_gui"/>
			</unit:plugins>

			<unit:codegen/>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/imageprocessing/MarkerPosition.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Marker Position">
			<unit:typeTemplates/>

			<unit:connectors>
				<unit:in>
					<unit:connector var:type="image" var:varname="image"/>
					<unit:connector var:type="int32" var:varname="id">
						<var:default var:val="-1"/>
					</unit:connector>
					<unit:connector var:type="bool" var:varname="visualizeposition">
						<var:default var:val="false"/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="bool" var:varname="found">
						<var:default var:val="false"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="posx">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="posy">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="posz">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="rotx">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="roty">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="rotz">
						<var:default var:val="0"/>
					</unit:connector>
				</unit:out>
			</unit:connectors>

			<unit:state>
        <unit:statevar var:type="image" var:varname="imagevisualization"/>
      </unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="image" unit:side="left"/>
						<unit:layout unit:varname="id" unit:side="left"/>
            <unit:layout unit:varname="visualizeposition" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="found" unit:side="right"/>
						<unit:layout unit:varname="posx" unit:side="right"/>
						<unit:layout unit:varname="posy" unit:side="right"/>
						<unit:layout unit:varname="posz" unit:side="right"/>
						<unit:layout unit:varname="rotx" unit:side="right"/>
						<unit:layout unit:varname="roty" unit:side="right"/>
						<unit:layout unit:varname="rotz" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state/>

				<unit:description>
					<unit:name>Marker position</unit:name>
					<unit:icon unit:filename="icons/marker.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="image">
								<unit:description>Image</unit:description>
							</unit:info>
							<unit:info unit:varname="id">
								<unit:description>ID</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="found">
								<unit:description>Marker found</unit:description>
							</unit:info>
							<unit:info unit:varname="posx">
								<unit:description>x [m]</unit:description>
							</unit:info>
							<unit:info unit:varname="posy">
								<unit:description>y [m]</unit:description>
							</unit:info>
							<unit:info unit:varname="posz">
								<unit:description>z [m]</unit:description>
							</unit:info>
							<unit:info unit:varname="rotx">
								<unit:description>a [deg]</unit:description>
							</unit:info>
							<unit:info unit:varname="roty">
								<unit:description>b [deg]</unit:description>
							</unit:info>
							<unit:info unit:varname="rotz">
								<unit:description>c [deg]</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state/>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_imageprocessing_markerposition_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_imageprocessing_markerposition_gui"/>
			</unit:plugins>

		</unit:unittype>

	</unit:unittypes>
</unit:unit>
