=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/schema/unit.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	EasyLib XML Schema Definition

	Copyright (c) 2007-2010 Technische Universität München, Lehrstuhl Informatik VI
		http://www6.in.tum.de/

	Copyright (c) 2007-2010 REC GmbH
		http://www.servicerobotics.eu/
-->
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:kv="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:desc="http://easykit.informatik.tu-muenchen.de/schema/description"
	targetNamespace="http://easykit.informatik.tu-muenchen.de/schema/unit"
	attributeFormDefault="qualified"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
		schemaLocation="keyvalue.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/plugin"
		schemaLocation="plugin.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/translation"
		schemaLocation="translation.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/template"
		schemaLocation="template.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/variable"
		schemaLocation="variable.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/description"
		schemaLocation="description.xsd"/>

	<xs:element name="unit">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">

				<!-- The translations element specifies translations for key phrases specified
				     below this device specification. See the translation.xsd schema file for how
				     the element and its children are to be specified. -->
				<xs:element name="translations" type="tr:translationType" minOccurs="0" maxOccurs="1"/>

				<xs:element name="unittypes" type="unit:unittypesType" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="unittypesType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="unittype" type="unit:unittypeType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unittypeType">
		<xs:sequence>
			<xs:element name="typeTemplates">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="typeTemplate" type="var:typeTemplateType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="statevar" type="unit:stateVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="guiinfo" type="unit:guiinfoType"/>

			<xs:element name="plugins" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="plugin" type="plugin:pluginType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="codegen" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="global" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="local" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="start" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="step" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="stop" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="connectorSideType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top"/>
			<xs:enumeration value="bottom"/>
			<xs:enumeration value="left"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="in"/>
			<xs:enumeration value="out"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="descriptionType">
		<xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="name" type="unit:briefDescription"/>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:element name="detailed" type="xs:string"/>
			</xs:sequence>
			<xs:sequence>
				<xs:choice>
					<xs:element name="icon" type="unit:filespec"/>
					<xs:element name="iconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:choice>
					<xs:element name="schematicIcon" type="unit:filespec"/>
					<xs:element name="schematicIconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="info" type="unit:stateVariableDescriptionType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="briefDescription">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="filespec">
		<xs:attribute type="xs:string" name="filename" use="required"/>
	</xs:complexType>

	<xs:complexType name="guiinfoType">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="1" name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="1" maxOccurs="1" name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="layout" type="unit:stateVariableGuiInfoType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description" type="unit:descriptionType"/>

			<!-- Optional list of annotations that can be used to categorize this item.
			     Reserved annotations:
			      * skill (int)         Denotes the level of difficulty of this item.
			      * keywords (keyValue) Child element containing keywords that can be used
			                            to define search terms for items.
			-->
			<xs:element minOccurs="0" maxOccurs="1" name="annotations" type="kv:keyValueRootType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="variableGuiInfoType">
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="side" type="unit:connectorSideType" use="required"/>
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
				<xs:attribute name="valueDisplay" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="variableDisplayType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible"/>
			<xs:enumeration value="hidden"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="variableDescriptionType">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="pluginType">
		<xs:attribute type="xs:string" name="easygenfilename" use="optional"/>
		<xs:attribute type="xs:string" name="easylabfilename" use="optional"/>
	</xs:complexType>

	<xs:complexType name="implType" mixed="true"/>

</xs:schema>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/dataexchange/ValueReader.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Value Reader">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="bool" var:varname="enable">
						<var:default var:val="true"/>
					</unit:connector>
					<unit:connector var:type="string" var:varname="file">
						<var:default var:val=""/>
					</unit:connector>
				</unit:in>
				<unit:out>
          <unit:connector var:type="floatvector" var:varname="output">
            <var:default var:val=""/>
          </unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
				<unit:statevar var:type="int16" var:varname="step">
					<var:default var:val="0"/>
				</unit:statevar>
        <unit:statevar var:type="bool" var:varname="running">
          <var:default var:val="false"/>
        </unit:statevar>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="enable" unit:side="left"/>
            <unit:layout unit:varname="file" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
            <unit:layout unit:varname="output" unit:side="right"/>
          </unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>Value reader</unit:name>
					<unit:icon unit:filename="icons/valuereader.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="enable">
								<unit:description>Enable</unit:description>
							</unit:info>
							<unit:info unit:varname="file">
								<unit:description>File</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
              <unit:info unit:varname="output">
                <unit:description>Output</unit:description>
              </unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
						<unit:info unit:varname="step">
							<unit:description>step</unit:description>
						</unit:info>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_dataexchange_valuereader_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_dataexchange_valuereader_gui"/>
			</unit:plugins>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/imageprocessing/ROI.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH ROI">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="image" var:varname="source">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="roi" var:varname="roi" >
						<var:default var:val=""/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="image" var:varname="dest">
						<var:default var:val=""/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="source" unit:side="left"/>
						<unit:layout unit:varname="roi" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="dest" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>ROI</unit:name>
					<unit:icon unit:filename="icons/roi.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="source">
								<unit:description>Input</unit:description>
							</unit:info>
							<unit:info unit:varname="roi">
								<unit:description>ROI</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="dest">
								<unit:description>Output</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_imageprocessing_roi_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_imageprocessing_roi_gui"/>
			</unit:plugins>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/math/ArithOps/Add.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>
		<unit:unittype unit:id="REC GmbH Basic Addition">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="float" var:varname="s1">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s2">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s3">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s4">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s5">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s6">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s7">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s8">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s9">
						<var:default var:val="0" />
					</unit:connector>
					<unit:connector var:type="float" var:varname="s10">
						<var:default var:val="0" />
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="float" var:varname="sum">
						<var:default var:val="0" />
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state/>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="s1" unit:side="left"/>
						<unit:layout unit:varname="s2" unit:side="left"/>
						<unit:layout unit:varname="s3" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s4" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s5" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s6" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s7" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s8" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s9" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="s10" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="sum" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state/>

				<unit:description>
					<unit:name>Addition</unit:name>
					<unit:icon unit:filename="add.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="s1">
								<unit:description>Summand[ 1]</unit:description>
							</unit:info>
							<unit:info unit:varname="s2">
								<unit:description>Summand[ 2]</unit:description>
							</unit:info>
							<unit:info unit:varname="s3">
								<unit:description>Summand[ 3]</unit:description>
							</unit:info>
							<unit:info unit:varname="s4">
								<unit:description>Summand[ 4]</unit:description>
							</unit:info>
							<unit:info unit:varname="s5">
								<unit:description>Summand[ 5]</unit:description>
							</unit:info>
							<unit:info unit:varname="s6">
								<unit:description>Summand[ 6]</unit:description>
							</unit:info>
							<unit:info unit:varname="s7">
								<unit:description>Summand[ 7]</unit:description>
							</unit:info>
							<unit:info unit:varname="s8">
								<unit:description>Summand[ 8]</unit:description>
							</unit:info>
							<unit:info unit:varname="s9">
								<unit:description>Summand[ 9]</unit:description>
							</unit:info>
							<unit:info unit:varname="s10">
								<unit:description>Summand[ 10]</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="sum">
								<unit:description>Sum</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state/>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_math_addition_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_math_addition_gui"/>
			</unit:plugins>
			
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/navigation/PoseComposer.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Pose Composer">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="float" var:varname="x">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="y">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="phi">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="bool" var:varname="pose_valid">
						<var:default var:val="true"/>
					</unit:connector>
					<unit:connector var:type="bool" var:varname="orientation_valid">
						<var:default var:val="true"/>
					</unit:connector>
					<unit:connector var:type="bool" var:varname="orientation_radians">
						<var:default var:val="false"/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="pose" var:varname="pose">
						<var:default var:val=""/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="x" unit:side="left"/>
						<unit:layout unit:varname="y" unit:side="left"/>
						<unit:layout unit:varname="phi" unit:side="left"/>
						<unit:layout unit:varname="pose_valid" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="orientation_valid" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="orientation_radians" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="pose" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>Pose composer</unit:name>
					<unit:icon unit:filename="icons/icon.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="x">
								<unit:description>x</unit:description>
							</unit:info>
							<unit:info unit:varname="y">
								<unit:description>y</unit:description>
							</unit:info>
							<unit:info unit:varname="phi">
								<unit:description>phi</unit:description>
							</unit:info>
							<unit:info unit:varname="pose_valid">
								<unit:description>Pose valid</unit:description>
							</unit:info>
							<unit:info unit:varname="orientation_valid">
								<unit:description>Orientation valid</unit:description>
							</unit:info>
							<unit:info unit:varname="orientation_radians">
								<unit:description>Orientation in radians</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="pose">
								<unit:description>Pose</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_navigation_pose_composer_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_navigation_pose_composer_gui"/>
			</unit:plugins>

			<unit:codegen/>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>
