=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/schema/unit.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
	EasyLib XML Schema Definition

	Copyright (c) 2007-2010 Technische Universität München, Lehrstuhl Informatik VI
		http://www6.in.tum.de/

	Copyright (c) 2007-2010 REC GmbH
		http://www.servicerobotics.eu/
-->
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:kv="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:desc="http://easykit.informatik.tu-muenchen.de/schema/description"
	targetNamespace="http://easykit.informatik.tu-muenchen.de/schema/unit"
	attributeFormDefault="qualified"
	elementFormDefault="qualified">

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/keyvalue"
		schemaLocation="keyvalue.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/plugin"
		schemaLocation="plugin.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/translation"
		schemaLocation="translation.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/template"
		schemaLocation="template.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/variable"
		schemaLocation="variable.xsd"/>

	<xs:import
		namespace="http://easykit.informatik.tu-muenchen.de/schema/description"
		schemaLocation="description.xsd"/>

	<xs:element name="unit">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">

				<!-- The translations element specifies translations for key phrases specified
				     below this device specification. See the translation.xsd schema file for how
				     the element and its children are to be specified. -->
				<xs:element name="translations" type="tr:translationType" minOccurs="0" maxOccurs="1"/>

				<xs:element name="unittypes" type="unit:unittypesType" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="unittypesType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="unittype" type="unit:unittypeType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unittypeType">
		<xs:sequence>
			<xs:element name="typeTemplates">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="typeTemplate" type="var:typeTemplateType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="connector" type="unit:connectorType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="statevar" type="unit:stateVarType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="guiinfo" type="unit:guiinfoType"/>

			<xs:element name="plugins" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="plugin" type="plugin:pluginType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="codegen" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="global" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="local" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="start" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="step" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
						<xs:element name="stop" type="tmpl:toolChainListType" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVarType">
		<xs:complexContent>
			<xs:extension base="var:variableType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="connectorSideType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top"/>
			<xs:enumeration value="bottom"/>
			<xs:enumeration value="left"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="in"/>
			<xs:enumeration value="out"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="descriptionType">
		<xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="name" type="unit:briefDescription"/>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:element name="detailed" type="xs:string"/>
			</xs:sequence>
			<xs:sequence>
				<xs:choice>
					<xs:element name="icon" type="unit:filespec"/>
					<xs:element name="iconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:sequence maxOccurs="1" minOccurs="0">
				<xs:choice>
					<xs:element name="schematicIcon" type="unit:filespec"/>
					<xs:element name="schematicIconSpec" type="desc:iconType"/>
				</xs:choice>
			</xs:sequence>
			<xs:element name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="in" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="out" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="info" type="unit:connectorDescriptionType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="info" type="unit:stateVariableDescriptionType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="briefDescription">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="filespec">
		<xs:attribute type="xs:string" name="filename" use="required"/>
	</xs:complexType>

	<xs:complexType name="guiinfoType">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="1" name="connectors">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="1" name="in">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="1" maxOccurs="1" name="out">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element maxOccurs="unbounded" name="layout" type="unit:connectorGuiInfoType"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="state">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="layout" type="unit:stateVariableGuiInfoType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="description" type="unit:descriptionType"/>

			<!-- Optional list of annotations that can be used to categorize this item.
			     Reserved annotations:
			      * skill (int)         Denotes the level of difficulty of this item.
			      * keywords (keyValue) Child element containing keywords that can be used
			                            to define search terms for items.
			-->
			<xs:element minOccurs="0" maxOccurs="1" name="annotations" type="kv:keyValueRootType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="variableGuiInfoType">
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="side" type="unit:connectorSideType" use="required"/>
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
				<xs:attribute name="valueDisplay" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableGuiInfoType">
		<xs:complexContent>
			<xs:extension base="unit:variableGuiInfoType">
				<xs:attribute name="display" type="unit:variableDisplayType" default="visible" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="variableDisplayType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="visible"/>
			<xs:enumeration value="hidden"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="variableDescriptionType">
		<xs:sequence>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="varname" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="connectorDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="stateVariableDescriptionType">
		<xs:complexContent>
			<xs:extension base="unit:variableDescriptionType"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="pluginType">
		<xs:attribute type="xs:string" name="easygenfilename" use="optional"/>
		<xs:attribute type="xs:string" name="easylabfilename" use="optional"/>
	</xs:complexType>

	<xs:complexType name="implType" mixed="true"/>

</xs:schema>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/math/Arrays/FloatArrayComposer.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>
		<unit:unittype unit:id="REC GmbH Float Array Composer">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="floatvector" var:varname="i1">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i2">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i3">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i4">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i5">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i6">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i7">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i8">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i9">
						<var:default var:val="" />
					</unit:connector>
					<unit:connector var:type="floatvector" var:varname="i10">
						<var:default var:val="" />
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="floatvector" var:varname="array">
						<var:default var:val="" />
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state/>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="i1" unit:side="left"/>
						<unit:layout unit:varname="i2" unit:side="left"/>
						<unit:layout unit:varname="i3" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i4" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i5" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i6" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i7" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i8" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i9" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="i10" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="array" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state/>

				<unit:description>
					<unit:name>Float array composer</unit:name>
					<unit:icon unit:filename="icon.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="i1">
								<unit:description>Index[ 1]</unit:description>
							</unit:info>
							<unit:info unit:varname="i2">
								<unit:description>Index[ 2]</unit:description>
							</unit:info>
							<unit:info unit:varname="i3">
								<unit:description>Index[ 3]</unit:description>
							</unit:info>
							<unit:info unit:varname="i4">
								<unit:description>Index[ 4]</unit:description>
							</unit:info>
							<unit:info unit:varname="i5">
								<unit:description>Index[ 5]</unit:description>
							</unit:info>
							<unit:info unit:varname="i6">
								<unit:description>Index[ 6]</unit:description>
							</unit:info>
							<unit:info unit:varname="i7">
								<unit:description>Index[ 7]</unit:description>
							</unit:info>
							<unit:info unit:varname="i8">
								<unit:description>Index[ 8]</unit:description>
							</unit:info>
							<unit:info unit:varname="i9">
								<unit:description>Index[ 9]</unit:description>
							</unit:info>
							<unit:info unit:varname="i10">
								<unit:description>Index[ 10]</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="array">
								<unit:description>Array</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state/>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_array_floatarraycomposer_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_array_floatarraycomposer_gui"/>
			</unit:plugins>
			
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/navigation/PositionView.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Position View">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="float" var:varname="xactual">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="yactual">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="phiactual">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="xset_in">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="yset_in">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="phiset_in">
						<var:default var:val="0"/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="float" var:varname="xset">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="yset">
						<var:default var:val="0"/>
					</unit:connector>
					<unit:connector var:type="float" var:varname="phiset">
						<var:default var:val="0"/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="xactual" unit:side="left"/>
						<unit:layout unit:varname="yactual" unit:side="left"/>
						<unit:layout unit:varname="phiactual" unit:side="left"/>
						<unit:layout unit:varname="xset_in" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="yset_in" unit:side="left" unit:display="hidden"/>
						<unit:layout unit:varname="phiset_in" unit:side="left" unit:display="hidden"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="xset" unit:side="right"/>
						<unit:layout unit:varname="yset" unit:side="right"/>
						<unit:layout unit:varname="phiset" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>Position View</unit:name>
					<unit:icon unit:filename="icons/positionview.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="xactual">
								<unit:description>x actual</unit:description>
							</unit:info>
							<unit:info unit:varname="yactual">
								<unit:description>y actual</unit:description>
							</unit:info>
							<unit:info unit:varname="phiactual">
								<unit:description>phi actual</unit:description>
							</unit:info>
							<unit:info unit:varname="xset_in">
								<unit:description>x set in</unit:description>
							</unit:info>
							<unit:info unit:varname="yset_in">
								<unit:description>y set in</unit:description>
							</unit:info>
							<unit:info unit:varname="phiset_in">
								<unit:description>phi set in</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="xset">
								<unit:description>x set</unit:description>
							</unit:info>
							<unit:info unit:varname="yset">
								<unit:description>y set</unit:description>
							</unit:info>
							<unit:info unit:varname="phiset">
								<unit:description>phi set</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_navigation_positionview_simulation"/>
				<unit:plugin plugin:type="dialog" plugin:library="unit_robview_navigation_positionview_gui"/>
			</unit:plugins>

			<unit:codegen/>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>

=== proffessorx/robotino/robotino-ros-pkg/robotino_core/copied/opt/robview3/units/robview/navigation/PathDecomposer.unit/unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit:unit
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://easykit.informatik.tu-muenchen.de/schema/unit unit.xsd"
	xmlns:plugin="http://easykit.informatik.tu-muenchen.de/schema/plugin"
	xmlns:unit="http://easykit.informatik.tu-muenchen.de/schema/unit"
	xmlns:var="http://easykit.informatik.tu-muenchen.de/schema/variable"
	xmlns:tmpl="http://easykit.informatik.tu-muenchen.de/schema/template"
	xmlns:tr="http://easykit.informatik.tu-muenchen.de/schema/translation">

	<unit:translations>
	</unit:translations>

	<unit:unittypes>

		<unit:unittype unit:id="REC GmbH Path Decomposer">
			<unit:typeTemplates/>
			<unit:connectors>
				<unit:in>
					<unit:connector var:type="path" var:varname="path">
						<var:default var:val=""/>
					</unit:connector>
					<unit:connector var:type="int32" var:varname="start">
						<var:default var:val="1"/>
					</unit:connector>
					<unit:connector var:type="int32" var:varname="length">
						<var:default var:val="1"/>
					</unit:connector>
				</unit:in>
				<unit:out>
					<unit:connector var:type="path" var:varname="subpath">
						<var:default var:val=""/>
					</unit:connector>
				</unit:out>
			</unit:connectors>
			<unit:state>
			</unit:state>

			<unit:guiinfo>
				<unit:connectors>
					<unit:in>
						<unit:layout unit:varname="path" unit:side="left"/>
						<unit:layout unit:varname="start" unit:side="left"/>
						<unit:layout unit:varname="length" unit:side="left"/>
					</unit:in>
					<unit:out>
						<unit:layout unit:varname="subpath" unit:side="right"/>
					</unit:out>
				</unit:connectors>
				<unit:state>
				</unit:state>

				<unit:description>
					<unit:name>Path decomposer</unit:name>
					<unit:icon unit:filename="icons/icon.png"/>
					<unit:connectors>
						<unit:in>
							<unit:info unit:varname="path">
								<unit:description>Path</unit:description>
							</unit:info>
							<unit:info unit:varname="start">
								<unit:description>Start</unit:description>
							</unit:info>
							<unit:info unit:varname="length">
								<unit:description>Length</unit:description>
							</unit:info>
						</unit:in>
						<unit:out>
							<unit:info unit:varname="subpath">
								<unit:description>Subpath</unit:description>
							</unit:info>
							<unit:info unit:varname="p0">
								<unit:description>Path[ 1]</unit:description>
							</unit:info>
							<unit:info unit:varname="p1">
								<unit:description>Path[ 2]</unit:description>
							</unit:info>
							<unit:info unit:varname="p2">
								<unit:description>Path[ 3]</unit:description>
							</unit:info>
							<unit:info unit:varname="p3">
								<unit:description>Path[ 4]</unit:description>
							</unit:info>
							<unit:info unit:varname="p4">
								<unit:description>Path[ 5]</unit:description>
							</unit:info>
							<unit:info unit:varname="p5">
								<unit:description>Path[ 6]</unit:description>
							</unit:info>
							<unit:info unit:varname="p6">
								<unit:description>Path[ 7]</unit:description>
							</unit:info>
							<unit:info unit:varname="p7">
								<unit:description>Path[ 8]</unit:description>
							</unit:info>
							<unit:info unit:varname="p8">
								<unit:description>Path[ 9]</unit:description>
							</unit:info>
							<unit:info unit:varname="p9">
								<unit:description>Path[ 10]</unit:description>
							</unit:info>
							<unit:info unit:varname="p10">
								<unit:description>Path[ 11]</unit:description>
							</unit:info>
							<unit:info unit:varname="p11">
								<unit:description>Path[ 12]</unit:description>
							</unit:info>
							<unit:info unit:varname="p12">
								<unit:description>Path[ 13]</unit:description>
							</unit:info>
							<unit:info unit:varname="p13">
								<unit:description>Path[ 14]</unit:description>
							</unit:info>
							<unit:info unit:varname="p14">
								<unit:description>Path[ 15]</unit:description>
							</unit:info>
							<unit:info unit:varname="p15">
								<unit:description>Path[ 16]</unit:description>
							</unit:info>
							<unit:info unit:varname="p16">
								<unit:description>Path[ 17]</unit:description>
							</unit:info>
							<unit:info unit:varname="p17">
								<unit:description>Path[ 18]</unit:description>
							</unit:info>
							<unit:info unit:varname="p18">
								<unit:description>Path[ 19]</unit:description>
							</unit:info>
							<unit:info unit:varname="p19">
								<unit:description>Path[ 20]</unit:description>
							</unit:info>
						</unit:out>
					</unit:connectors>
					<unit:state>
					</unit:state>
				</unit:description>
			</unit:guiinfo>

			<unit:plugins>
				<unit:plugin plugin:type="simulation" plugin:library="unit_robview_navigation_path_decomposer_simulation"/>
				<!--<unit:plugin plugin:type="dialog" plugin:library="unit_robview_navigation_path_decomposer_gui"/>-->
			</unit:plugins>

			<unit:codegen/>
		</unit:unittype>
	</unit:unittypes>
</unit:unit>
